//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.18051
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

[AddComponentMenu("Activation")]
public class Activation : MonoBehaviour
{
	void Start()
	{

	}

	void Update()
	{

	}

	public void activate()
	{

	}

	public void deactivate()
	{
	}
}

