//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.18051
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

[AddComponentMenu("Level0 End")]
public class Level0_end : MonoBehaviour
{
	public GameObject[] player = new GameObject[]{null,null};
	public float radius = 2;
	void Start()
	{
		player = new GameObject[]{GameObject.Find("Player1"),GameObject.Find("Player2")};
	}

	void Update()
	{
		bool do_end = true;
		for (int i=0; i<player.Length; i++)
		{
			if (Vector3.Distance (player[i].transform.position, transform.position) > radius)
			{
				do_end = false;
				break;
			}
		}

		if (do_end)
		{
			for (int i=0; i<player.Length; i++)
			{
				player[i].transform.position = GameObject.Find("Level1/Player"+(i+1)+"_StartingPos").gameObject.transform.position;
			}
		}
	}
}
