//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.18051
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

[AddComponentMenu("Level1_activation_torch1")]
public class Level1_activation_torch1 : Activation
{
	public GameObject sensorToActivate;
	public GameObject light_cylinder;
	public Light light;

	void Start()
	{
		light_cylinder.renderer.enabled = false;
		light.enabled = false;
	}

	public void activate()
	{
//		Debug.Log ("sensor1 activation...");
		sensorToActivate.GetComponent<Level1_activation_sensor2> ().activate();
		light_cylinder.renderer.enabled = true;
		light.enabled = true;
	}
	public void deactivate()
	{
		sensorToActivate.GetComponent<Level1_activation_sensor2> ().deactivate();
		light_cylinder.renderer.enabled = false;
		light.enabled = false;
	}
}

